server:
  port: 8080

security:
  jwt:
    key-store: classpath:keystore.jks
    key-store-password: 123456
    key-pair-alias: servercert
    key-pair-password: 1234

spring:
  datasource:
    initialization-mode: never
    url:
    username: root
    password: root
